### ISSUE TITLE
Warning in XCode 7

### ISSUE THREAD

**Issue by beemaster** [c42f/tinyformat#28]
After updating to XCode 7 I have following warning:

    tinyformat.h:864:27: error: field 'm_formatterStore' is uninitialized when used here [-Werror,-Wuninitialized]
                : FormatList(&m_formatterStore[0], N),

I wish I could do a pull request but I can not wrap my head around how this could be fixed.

**Comment by c42f** [comment]
This probably happens because the value `m_formatterStore[0]` is indeed uninitialized at that point (it gets initialized on the next line).  However, the warning is spurious because the *address* `&m_formatterStore[0]` is perfectly well defined, and is not dereferenced until later.  What happens if you replace `&m_formatterStore[0]` with `m_formatterStore.data()`?

If that doesn't help, another option is to disable the -wuninitialized warning on this one line, using `#pragma GCC diagnostic ignored "-Wuninitialized"`, the associated pragma warning push/pop dance, and `#ifdefs` for the specific version of clang.  It'll be ugly ;-)

**Comment by c42f** [comment]
On second thoughts, taking `&m_formatterStore[0]` when the store is a `std::array` is technically an error (albeit a harmless one), since it calls `operator[]` on an uninitialized object.  I think the better solution here is to just revert to a plain old C style array for `m_formatterStore` where taking a reference is clearly harmless.

I've done this and it seems to pass all the tests on windows VS2013,VS2015 and linux gcc-4.8, clang-3.7.  I did manage to reproduce your warnings with clang-3.7 on linux so hopefully this will also fix your problems on xcode 7.  Let me know how it works for you.

**Comment by beemaster** [comment]
Yes, it helped. Thanks!

**Comment by c42f** [comment]
Great, thanks for the follow up!
