### ISSUE TITLE
Compile error is vc2010

### ISSUE THREAD

**Issue by ccpaging** [c42f/tinyformat#31]
`
// Format at most ntrunc characters to the given stream.
template<typename T>
inline void formatTruncated(std::ostream& out, const T& value, int ntrunc)
{
    std::ostringstream tmp;
    tmp << value;
    std::string result = tmp.str();
    out.write(result.c_str(), std::min(ntrunc, static_cast<int>(result.size())));
}
`

"std::min" should be changed to "min"

**Comment by c42f** [comment]
Thanks for the report.  This is due to an unfortunate `#define` of `min` in `windows.h`.  I've fixed this with the standard workaround in 0586189016 which is to disable the macro expansion with an extra set of brackets.

If you want to avoid some of the extra junk defined by windows.h, you could fix this in your own code by `#define NOMINMAX`. (For good measure I'd usually also include `#define VC_EXTRALEAN` and `#define WIN32_LEAN_AND_MEAN` in cross platform code.  Depends what you're doing.)

**Comment by ccpaging** [comment]
@c42f Thank you. It is working.
