### ISSUE TITLE
Support CString in VC

### ISSUE THREAD

**Issue by ccpaging** [c42f/tinyformat#34]
Now I use following code in VC2010:

```
#include "tinyformat.h"
#define MAKE_CSTRING_FORMAT_FUNC(n)	\
template<TINYFORMAT_ARGTYPES(n)>    \
CString csFormat(const char* fmt, TINYFORMAT_VARARGS(n))	\
{	\
	std::string m = tfm::format(fmt, TINYFORMAT_PASSARGS(n));	\
	return CString(m.c_str());	\
}
TINYFORMAT_FOREACH_ARGNUM(MAKE_CSTRING_FORMAT_FUNC)
```

Call it by:

```
CString sMsg = csFormat("%i %s", i, s);
```

**Comment by c42f** [comment]
It would be possible to add this to a different header `contrib/tinyformat_win.h` for example, but it seems a bit out of scope for tinyformat.h itself since the focus there is on the std library and narrow-char only at the moment.

For more natural windows support, we'd presumably have to also deal with the complication of wchar strings, particularly since CString appears to be based on TChar

**Comment by c42f** [comment]
For now I think I'll close this, as it doesn't interest me for the core tinyformat header to have any more compiler-dependent code. However, I'd potentially accept a nicely written PR putting the functionality into a separate header.

Thanks for note in any case :)
